@GameListing.Api_HostAddress = https://localhost:7179

GET {{GameListing.Api_HostAddress}}/api/games

###

POST {{GameListing.Api_HostAddress}}/api/games
Content-Type: application/json

{
    "Title": "Test Game3",
    "Category": "FPS",
    "ReleaseDate": "2024-10-25",
    "Price": 69.99,
    "PlayerIds": [1, 2]
}

###

@id=4
DELETE {{GameListing.Api_HostAddress}}/api/games/{{id}}

###

GET {{GameListing.Api_HostAddress}}/api/games/{{id}}

###

PUT {{GameListing.Api_HostAddress}}/api/games/{{id}}
Content-Type: application/json

{
    "Id": 4,
    "Title": "Test Game put3",
    "Category": "FPS",
    "ReleaseDate": "2024-10-25",
    "Price": 69.99
}

###

GET {{GameListing.Api_HostAddress}}/api/countries

###

POST {{GameListing.Api_HostAddress}}/api/countries
Content-Type: application/json

{
    "Name": "Test Country1",
    "PlayerIds": [1, 2]
}

###

DELETE {{GameListing.Api_HostAddress}}/api/countries/{{id}}

###

GET {{GameListing.Api_HostAddress}}/api/countries/{{id}}

###

PUT {{GameListing.Api_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
    "Id": 4,
    "Name": "Test Country Put3",
    "PlayerIds": [3]
}

###

GET {{GameListing.Api_HostAddress}}/api/players

###

POST {{GameListing.Api_HostAddress}}/api/players
Content-Type: application/json

{
    "Username": "Test Player",
    "Email": "test3@test.com",
    "CountryId": 3,
    "GameIds": [1, 2]
}

###

DELETE {{GameListing.Api_HostAddress}}/api/players/{{id}}

###

GET {{GameListing.Api_HostAddress}}/api/players/{{id}}

###

PUT {{GameListing.Api_HostAddress}}/api/players/{{id}}
Content-Type: application/json

{
    "Id": 4,
    "Username": "Test Player Put",
    "Email": "test4@test.com",
    "CountryId": 2
}

###
